pipeline {

agent any

parameters {

choice(

name:'ACTION',

choices:['APPLY','DESTROY'],

description:'Terraform operation'

)

}

stages {

stage('Checkout') {

steps {

git branch:'main',

url:'https://github.com/anay2609/anayterraform.git'

}

}

stage('Terraform Init') {

steps {

dir('gcp') {

withCredentials([

file(

credentialsId:'gcp-creds',

variable:'GCPKEY'

)

]) {

sh '''

cp $GCPKEY terraform-gcp.json

export GOOGLE_APPLICATION_CREDENTIALS=terraform-gcp.json

terraform init

'''

}

}

}

}

stage('Plan') {

when {

expression {

params.ACTION=="APPLY"

}

}

steps {

dir('gcp') {

sh 'terraform plan'

}

}

}

stage('Apply') {

when {

expression {

params.ACTION=="APPLY"

}

}

steps {

dir('gcp') {

sh 'terraform apply -auto-approve'

}

}

}

stage('Destroy') {

when {

expression {

params.ACTION=="DESTROY"

}

}

steps {

input "Destroy GCP infra?"

dir('gcp') {

sh 'terraform destroy -auto-approve'

}

}

}

}

}
