pipeline {

    agent any

    parameters {

        choice(
            name: 'ACTION',
            choices: ['APPLY', 'DESTROY'],
            description: 'Terraform operation'
        )

    }

    stages {

        stage('Checkout') {

            steps {

                git(
                    branch: 'main',
                    url: 'https://github.com/anay2609/anayterraform.git'
                )

            }

        }

        stage('Terraform Init') {

            steps {

                dir('gcp') {

                    withCredentials([

                        file(
                            credentialsId: 'gcp-creds',
                            variable: 'GCPKEY'
                        )

                    ]) {

                        sh '''

                        export GOOGLE_APPLICATION_CREDENTIALS=$GCPKEY

                        terraform init

                        '''

                    }

                }

            }

        }

        stage('Validate') {

            steps {

                dir('gcp') {

                    withCredentials([

                        file(
                            credentialsId: 'gcp-creds',
                            variable: 'GCPKEY'
                        )

                    ]) {

                        sh '''

                        export GOOGLE_APPLICATION_CREDENTIALS=$GCPKEY

                        terraform validate

                        '''

                    }

                }

            }

        }

        stage('Plan') {

            when {

                expression {

                    params.ACTION == "APPLY"

                }

            }

            steps {

                dir('gcp') {

                    withCredentials([

                        file(
                            credentialsId: 'gcp-creds',
                            variable: 'GCPKEY'
                        )

                    ]) {

                        sh '''

                        export GOOGLE_APPLICATION_CREDENTIALS=$GCPKEY

                        terraform plan

                        '''

                    }

                }

            }

        }

        stage('Apply') {

            when {

                expression {

                    params.ACTION == "APPLY"

                }

            }

            steps {

                input "Proceed with GCP deployment?"

                dir('gcp') {

                    withCredentials([

                        file(
                            credentialsId: 'gcp-creds',
                            variable: 'GCPKEY'
                        )

                    ]) {

                        sh '''

                        export GOOGLE_APPLICATION_CREDENTIALS=$GCPKEY

                        terraform apply -auto-approve

                        '''

                    }

                }

            }

        }

        stage('Destroy') {

            when {

                expression {

                    params.ACTION == "DESTROY"

                }

            }

            steps {

                input "Destroy GCP infrastructure?"

                dir('gcp') {

                    withCredentials([

                        file(
                            credentialsId: 'gcp-creds',
                            variable: 'GCPKEY'
                        )

                    ]) {

                        sh '''

                        export GOOGLE_APPLICATION_CREDENTIALS=$GCPKEY

                        terraform destroy -auto-approve

                        '''

                    }

                }

            }

        }

    }

}
